version: "3"

services:
  bttr-proxy:
    image: traefik:v2.10
    container_name: bttr-proxy
    ports:
      - 80:80
      - 443:443
      - 5432:5432
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/etc/traefik
    networks:
      - bttr

networks:
  bttr:
    external: true
