global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  tcp:
    address: :5432

providers:
  docker:
    exposedByDefault: false
    network: bttr
